version: '3.8'
services:
  web:
    build: .
    volumes:
      - ./src:/var/www/html
    ports:
      - 8080:80
    depends_on:
      - db
    networks:
      - app-network
  db:
    image: mysql
    restart: always
    volumes:
      - ./db-data:/var/lib/mysql
      - ./php-ticket-booking-web.sql:/docker-entrypoint-initdb.d/php-ticket-booking-web.sql
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: php_ticket_booking_web
    ports:
      - 3306:3306
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
